### ISSUE TITLE
Mock fails inside GitHub Action

### ISSUE THREAD

**Issue by junghans** [rpm-software-management/mock#1570]
I have a simple Git hub Action (https://github.com/junghans/libcerf.spec/blob/rawhide/.github/workflows/continuous-integration-workflow.yml)
```yaml

name: CI
on:
  push:
    branches:
      - rawhide

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:rawhide
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install fedpkg
        run: dnf -y install fedpkg
      - name: Download source
        run: spectool -g libcerf.spec
      - name: Build rpm
        run: fedpkg mockbuild --mock-config /etc/mock/fedora-rawhide-s390x.cfg
```
but it fails with `Error: call to ldconfig failed.`?
(see https://github.com/junghans/libcerf.spec/actions/runs/14540748543/job/40798073135)

Any ideas how to fix that?
